-- ============================================================
-- Migration: 0010_work_orders.sql
-- Description: Core operational entity — work orders, items,
--   status history, check-in, assignments, and reworks.
--   Order number generation is concurrency-safe.
-- ============================================================

-- ─────────────────────────────────────────────
-- ORDER NUMBER SEQUENCE TABLE
-- One row per (organization, branch, year) — for safe concurrent number generation
-- ─────────────────────────────────────────────
create table public.order_number_sequences (
  organization_id uuid not null references public.organizations(id) on delete restrict,
  branch_code     text not null,
  year            int  not null,
  last_sequence   int  not null default 0,
  primary key (organization_id, branch_code, year)
);

comment on table public.order_number_sequences is 'Counter table for generating unique, readable order numbers. Use generate_order_number() RPC only.';

-- ─────────────────────────────────────────────
-- RPC: Generate order number (concurrency-safe)
-- Uses SELECT FOR UPDATE to prevent race conditions
-- Format: ESC-2026-000001
-- ─────────────────────────────────────────────
create or replace function public.generate_order_number(
  p_organization_id uuid,
  p_branch_code     text,
  p_year            int default extract(year from now())::int
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_next_seq int;
begin
  -- Upsert sequence row and lock it for this transaction
  insert into public.order_number_sequences (organization_id, branch_code, year, last_sequence)
  values (p_organization_id, p_branch_code, p_year, 0)
  on conflict (organization_id, branch_code, year) do nothing;

  -- Lock the row and increment atomically
  update public.order_number_sequences
  set last_sequence = last_sequence + 1
  where organization_id = p_organization_id
    and branch_code = p_branch_code
    and year = p_year
  returning last_sequence into v_next_seq;

  -- Format: ESC-2026-000001
  return p_branch_code || '-' || p_year || '-' || lpad(v_next_seq::text, 6, '0');
end;
$$;

-- ─────────────────────────────────────────────
-- WORK ORDERS
-- ─────────────────────────────────────────────
create table public.work_orders (
  id              uuid        primary key default gen_random_uuid(),
  organization_id uuid        not null references public.organizations(id) on delete restrict,
  branch_id       uuid        not null references public.branches(id) on delete restrict,
  order_number    text        not null unique,
  customer_id     uuid        references public.customers(id) on delete restrict,
  vehicle_id      uuid        references public.vehicles(id) on delete restrict,
  appointment_id  uuid,                    -- FK added after appointments table
  source          text        not null default 'walk_in'
                              check (source in ('walk_in','appointment','fleet','online','phone')),
  priority        text        not null default 'normal'
                              check (priority in ('normal','high','vip')),
  status          text        not null default 'received'
                              check (status in (
                                'received','waiting','washing','drying_detailing',
                                'quality_control','ready','paid','delivered','cancelled'
                              )),
  -- Timestamps for each status transition
  checked_in_at   timestamptz,
  started_at      timestamptz,
  completed_at    timestamptz,
  ready_at        timestamptz,
  delivered_at    timestamptz,
  cancelled_at    timestamptz,

  -- Financials (denormalized for performance; always recalculated before save)
  subtotal        numeric(10,2) not null default 0,
  discount_total  numeric(10,2) not null default 0,
  tax_total       numeric(10,2) not null default 0,
  tip_total       numeric(10,2) not null default 0,
  total           numeric(10,2) not null default 0,
  payment_status  text        not null default 'pending'
                              check (payment_status in ('pending','partial','paid','refunded')),
  notes           text,
  created_by      uuid        references public.profiles(id) on delete set null,
  updated_by      uuid        references public.profiles(id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

comment on table public.work_orders is 'Core operational entity. Every vehicle visit generates one work order.';
comment on column public.work_orders.order_number is 'Human-readable unique number (e.g. ESC-2026-000001). Generated by generate_order_number() RPC.';
comment on column public.work_orders.subtotal is 'Sum of item totals before tax/discount. Recalculated on every item change.';

create trigger work_orders_updated_at
  before update on public.work_orders
  for each row execute function public.set_updated_at();

create index idx_work_orders_org_branch on public.work_orders(organization_id, branch_id);
create index idx_work_orders_branch_status on public.work_orders(branch_id, status);
create index idx_work_orders_branch_created on public.work_orders(branch_id, created_at desc);
create index idx_work_orders_customer_id on public.work_orders(customer_id);
create index idx_work_orders_vehicle_id on public.work_orders(vehicle_id);
create index idx_work_orders_payment_status on public.work_orders(branch_id, payment_status);

alter table public.work_orders enable row level security;

create policy "work_orders_select"
  on public.work_orders for select
  using (
    branch_id in (select public.get_accessible_branch_ids())
    and public.has_permission('orders.read')
  );

-- Insert/update goes through create_work_order() RPC
-- Direct writes blocked; RPC uses security definer
create policy "work_orders_update_direct"
  on public.work_orders for update
  using (
    branch_id in (select public.get_accessible_branch_ids())
    and public.has_permission('orders.update')
  );

-- ─────────────────────────────────────────────
-- WORK ORDER ITEMS
-- ─────────────────────────────────────────────
create table public.work_order_items (
  id                    uuid          primary key default gen_random_uuid(),
  work_order_id         uuid          not null references public.work_orders(id) on delete cascade,
  service_id            uuid          not null references public.services(id) on delete restrict,
  description_snapshot  text          not null,   -- service name at time of sale (immutable)
  price_snapshot        numeric(10,2) not null,   -- listed price (before discount/tax)
  quantity              int           not null default 1 check (quantity > 0),
  unit_price            numeric(10,2) not null,   -- effective unit price (may equal price_snapshot)
  discount_amount       numeric(10,2) not null default 0 check (discount_amount >= 0),
  tax_amount            numeric(10,2) not null default 0 check (tax_amount >= 0),
  total                 numeric(10,2) not null,   -- (unit_price * qty) - discount + tax
  membership_covered    boolean       not null default false,
  membership_usage_id   uuid,                     -- FK added after memberships table
  sort_order            int           not null default 0,
  created_at            timestamptz   not null default now()
);

comment on table public.work_order_items is 'Line items of a work order. description_snapshot and price_snapshot are immutable records of the sale.';

create index idx_work_order_items_work_order on public.work_order_items(work_order_id);
create index idx_work_order_items_service on public.work_order_items(service_id);

alter table public.work_order_items enable row level security;

create policy "work_order_items_select"
  on public.work_order_items for select
  using (
    work_order_id in (
      select id from public.work_orders
      where branch_id in (select public.get_accessible_branch_ids())
    )
    and public.has_permission('orders.read')
  );

-- ─────────────────────────────────────────────
-- WORK ORDER STATUS HISTORY
-- ─────────────────────────────────────────────
create table public.work_order_status_history (
  id              uuid        primary key default gen_random_uuid(),
  work_order_id   uuid        not null references public.work_orders(id) on delete cascade,
  previous_status text,
  new_status      text        not null,
  changed_by      uuid        references public.profiles(id) on delete set null,
  changed_at      timestamptz not null default now(),
  notes           text,
  source          text        not null default 'manual'
                              check (source in ('manual','system','api'))
);

comment on table public.work_order_status_history is 'Immutable audit trail of all status transitions. Used for operational KPI calculations.';

create index idx_wo_status_history_order on public.work_order_status_history(work_order_id);

alter table public.work_order_status_history enable row level security;

create policy "wo_status_history_select"
  on public.work_order_status_history for select
  using (
    work_order_id in (
      select id from public.work_orders
      where branch_id in (select public.get_accessible_branch_ids())
    )
    and public.has_permission('orders.read')
  );

-- ─────────────────────────────────────────────
-- TRIGGER: Auto-record status changes
-- ─────────────────────────────────────────────
create or replace function public.record_order_status_change()
returns trigger language plpgsql as $$
begin
  if new.status <> old.status then
    insert into public.work_order_status_history (
      work_order_id, previous_status, new_status, changed_by, source
    ) values (
      new.id, old.status, new.status, new.updated_by, 'manual'
    );

    -- Update relevant timestamp
    case new.status
      when 'washing'  then new.started_at = coalesce(new.started_at, now());
      when 'ready'    then new.ready_at = now();
      when 'paid'     then null;  -- set by payment RPC
      when 'delivered' then new.delivered_at = now();
      when 'cancelled' then new.cancelled_at = now();
      else null;
    end case;
  end if;
  return new;
end;
$$;

create trigger work_order_status_change
  before update on public.work_orders
  for each row execute function public.record_order_status_change();

-- ─────────────────────────────────────────────
-- VEHICLE CHECK-IN
-- ─────────────────────────────────────────────
create table public.vehicle_checkins (
  id                    uuid        primary key default gen_random_uuid(),
  work_order_id         uuid        not null unique references public.work_orders(id) on delete cascade,
  mileage               int,
  fuel_level            int         check (fuel_level between 0 and 8),  -- octavos de tanque
  valuables_declared    text,
  existing_damage_notes text,
  general_notes         text,
  received_by           uuid        references public.profiles(id) on delete set null,
  created_at            timestamptz not null default now()
);

comment on table public.vehicle_checkins is 'Vehicle condition at reception. One per work order. Photos in vehicle_media.';
comment on column public.vehicle_checkins.fuel_level is 'Fuel level in eighths (0-8). 8 = full tank.';

alter table public.vehicle_checkins enable row level security;

create policy "checkins_select"
  on public.vehicle_checkins for select
  using (
    work_order_id in (
      select id from public.work_orders
      where branch_id in (select public.get_accessible_branch_ids())
    )
    and public.has_permission('orders.read')
  );

-- ─────────────────────────────────────────────
-- WORK ORDER ASSIGNMENTS (employee → work)
-- ─────────────────────────────────────────────
create table public.work_order_assignments (
  id                  uuid        primary key default gen_random_uuid(),
  work_order_id       uuid        not null references public.work_orders(id) on delete cascade,
  work_order_item_id  uuid        references public.work_order_items(id) on delete cascade,
  employee_id         uuid        not null,    -- FK added after employees table in 0018
  role                text        not null,    -- 'washer', 'detailer', 'supervisor'
  started_at          timestamptz,
  completed_at        timestamptz,
  notes               text
);

comment on table public.work_order_assignments is 'Records which employee performed which service on which order. Source for employee KPIs.';

create index idx_wo_assignments_order on public.work_order_assignments(work_order_id);
create index idx_wo_assignments_employee on public.work_order_assignments(employee_id);

alter table public.work_order_assignments enable row level security;

create policy "wo_assignments_select"
  on public.work_order_assignments for select
  using (
    work_order_id in (
      select id from public.work_orders
      where branch_id in (select public.get_accessible_branch_ids())
    )
    and public.has_permission('orders.read')
  );

-- ─────────────────────────────────────────────
-- WORK ORDER REWORKS
-- ─────────────────────────────────────────────
create table public.work_order_reworks (
  id                      uuid        primary key default gen_random_uuid(),
  work_order_id           uuid        not null references public.work_orders(id) on delete restrict,
  work_order_item_id      uuid        references public.work_order_items(id),
  service_id              uuid        references public.services(id),
  reason                  text        not null,
  responsible_employee_id uuid,       -- FK added after employees table
  requested_by            uuid        references public.profiles(id) on delete set null,
  created_at              timestamptz not null default now(),
  completed_at            timestamptz
);

comment on table public.work_order_reworks is 'Records rework events. Never revert status directly — always log the rework event.';

alter table public.work_order_reworks enable row level security;
create index idx_wo_reworks_order on public.work_order_reworks(work_order_id);

create policy "wo_reworks_select"
  on public.work_order_reworks for select
  using (
    work_order_id in (
      select id from public.work_orders
      where branch_id in (select public.get_accessible_branch_ids())
    )
    and public.has_permission('quality.read')
  );

-- ─────────────────────────────────────────────
-- RPC: Create work order (transactional)
-- Creates order + items + initial status history
-- ─────────────────────────────────────────────
create or replace function public.create_work_order(
  p_branch_id     uuid,
  p_customer_id   uuid,
  p_vehicle_id    uuid,
  p_source        text default 'walk_in',
  p_priority      text default 'normal',
  p_notes         text default null,
  p_services      jsonb default '[]'::jsonb   -- [{service_id, quantity, unit_price, discount_amount}]
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org_id        uuid;
  v_branch_code   text;
  v_order_number  text;
  v_order_id      uuid;
  v_subtotal      numeric(10,2) := 0;
  v_tax_total     numeric(10,2) := 0;
  v_tax_rate      numeric(5,4) := 0;
  v_total         numeric(10,2) := 0;
  v_item          jsonb;
  v_service_name  text;
  v_item_total    numeric(10,2);
  v_item_tax      numeric(10,2);
  v_item_id       uuid;
  v_sort          int := 0;
begin
  -- Permission check
  if not public.has_permission('orders.create') then
    raise exception 'Permission denied: orders.create required';
  end if;

  -- Branch access check
  if p_branch_id not in (select public.get_accessible_branch_ids()) then
    raise exception 'Access denied to branch';
  end if;

  -- Get org_id and branch code
  select organization_id, code
  into v_org_id, v_branch_code
  from public.branches
  where id = p_branch_id;

  -- Get current tax rate
  select rate into v_tax_rate
  from public.tax_rates
  where organization_id = v_org_id
    and active = true
    and applicable_from <= current_date
    and (applicable_to is null or applicable_to >= current_date)
  order by applicable_from desc
  limit 1;

  -- Generate unique order number (concurrency-safe)
  v_order_number := public.generate_order_number(
    v_org_id,
    v_branch_code,
    extract(year from now())::int
  );

  -- Create the work order
  insert into public.work_orders (
    organization_id, branch_id, order_number,
    customer_id, vehicle_id, source, priority,
    notes, status, created_by
  ) values (
    v_org_id, p_branch_id, v_order_number,
    p_customer_id, p_vehicle_id, p_source, p_priority,
    p_notes, 'received', auth.uid()
  )
  returning id into v_order_id;

  -- Insert initial status history
  insert into public.work_order_status_history (
    work_order_id, previous_status, new_status, changed_by, source
  ) values (
    v_order_id, null, 'received', auth.uid(), 'system'
  );

  -- Insert service items
  for v_item in select * from jsonb_array_elements(p_services)
  loop
    v_sort := v_sort + 1;

    -- Get service name snapshot
    select name into v_service_name
    from public.services
    where id = (v_item->>'service_id')::uuid;

    -- Calculate totals
    v_item_total := (v_item->>'unit_price')::numeric * coalesce((v_item->>'quantity')::int, 1)
                    - coalesce((v_item->>'discount_amount')::numeric, 0);

    -- Apply tax only if service is taxable
    if exists (
      select 1 from public.services
      where id = (v_item->>'service_id')::uuid and taxable = true
    ) then
      v_item_tax := round(v_item_total * v_tax_rate, 2);
    else
      v_item_tax := 0;
    end if;

    insert into public.work_order_items (
      work_order_id, service_id,
      description_snapshot, price_snapshot,
      quantity, unit_price,
      discount_amount, tax_amount,
      total, sort_order
    ) values (
      v_order_id,
      (v_item->>'service_id')::uuid,
      v_service_name,
      (v_item->>'unit_price')::numeric,
      coalesce((v_item->>'quantity')::int, 1),
      (v_item->>'unit_price')::numeric,
      coalesce((v_item->>'discount_amount')::numeric, 0),
      v_item_tax,
      v_item_total + v_item_tax,
      v_sort
    )
    returning id into v_item_id;

    v_subtotal  := v_subtotal + (v_item_total);
    v_tax_total := v_tax_total + v_item_tax;
  end loop;

  v_total := v_subtotal + v_tax_total;

  -- Update order totals
  update public.work_orders
  set subtotal    = v_subtotal,
      tax_total   = v_tax_total,
      total       = v_total,
      checked_in_at = now()
  where id = v_order_id;

  return jsonb_build_object(
    'order_id',     v_order_id,
    'order_number', v_order_number,
    'subtotal',     v_subtotal,
    'tax_total',    v_tax_total,
    'total',        v_total
  );
end;
$$;

comment on function public.create_work_order(uuid, uuid, uuid, text, text, text, jsonb) is
  'Atomically creates a work order with items and initial status. Returns order ID and number.';
-- ============================================================
-- Migration: 0011_operations.sql
-- Description: Workstations, equipment, machine programs,
--   and resource assignment with concurrency protection.
-- ============================================================

-- ─────────────────────────────────────────────
-- WORKSTATIONS (Bahías/Estaciones)
-- ─────────────────────────────────────────────
create table public.workstations (
  id              uuid    primary key default gen_random_uuid(),
  organization_id uuid    not null references public.organizations(id) on delete restrict,
  branch_id       uuid    not null references public.branches(id) on delete restrict,
  code            text    not null,
  name            text    not null,
  type            text    not null check (type in ('wash','drying','detailing','vacuum','quality_control','reception')),
  status          text    not null default 'available'
                          check (status in ('available','occupied','maintenance','offline')),
  active          boolean not null default true,

  constraint workstations_branch_code_unique unique (branch_id, code)
);

comment on table public.workstations is 'Physical stations/bays in a branch. Realtime-enabled for live operations board.';

alter table public.workstations enable row level security;
create index idx_workstations_branch on public.workstations(branch_id);

create policy "workstations_select"
  on public.workstations for select
  using (
    branch_id in (select public.get_accessible_branch_ids())
  );

create policy "workstations_manage"
  on public.workstations for all
  using (
    branch_id in (select public.get_accessible_branch_ids())
    and public.has_permission('settings.manage')
  );

-- ─────────────────────────────────────────────
-- EQUIPMENT (Máquinas)
-- ─────────────────────────────────────────────
create table public.equipment (
  id              uuid    primary key default gen_random_uuid(),
  organization_id uuid    not null references public.organizations(id) on delete restrict,
  branch_id       uuid    not null references public.branches(id) on delete restrict,
  workstation_id  uuid    references public.workstations(id) on delete set null,
  equipment_type  text    not null,       -- 'tunnel_washer', 'pressure_washer', 'vacuum', etc.
  name            text    not null,
  code            text    not null,
  status          text    not null default 'available'
                          check (status in ('available','occupied','maintenance','offline')),
  active          boolean not null default true,
  installed_at    date,
  notes           text,

  constraint equipment_branch_code_unique unique (branch_id, code)
);

comment on table public.equipment is 'Physical machines. Status is Realtime-synced for live ops display.';

alter table public.equipment enable row level security;
create index idx_equipment_branch on public.equipment(branch_id);
create index idx_equipment_status on public.equipment(branch_id, status);

create policy "equipment_select"
  on public.equipment for select
  using (branch_id in (select public.get_accessible_branch_ids()));

create policy "equipment_manage"
  on public.equipment for all
  using (
    branch_id in (select public.get_accessible_branch_ids())
    and public.has_permission('settings.manage')
  );

-- ─────────────────────────────────────────────
-- MACHINE PROGRAMS
-- ─────────────────────────────────────────────
create table public.machine_programs (
  id              uuid    primary key default gen_random_uuid(),
  equipment_id    uuid    references public.equipment(id) on delete cascade,
  equipment_type  text,   -- for generic programs not tied to a specific machine
  code            text    not null,
  name            text    not null,
  duration_minutes int    check (duration_minutes > 0),
  active          boolean not null default true
);

comment on table public.machine_programs is 'Named wash programs. Never hardcode Program 1/2/3/4. Programs are configured per machine or machine type.';

alter table public.machine_programs enable row level security;
create index idx_machine_programs_equipment on public.machine_programs(equipment_id);

create policy "machine_programs_select"
  on public.machine_programs for select
  using (
    equipment_id is null
    or equipment_id in (
      select id from public.equipment
      where branch_id in (select public.get_accessible_branch_ids())
    )
  );

-- ─────────────────────────────────────────────
-- SERVICE → MACHINE PROGRAM mapping
-- ─────────────────────────────────────────────
create table public.service_machine_programs (
  service_id          uuid not null references public.services(id) on delete cascade,
  machine_program_id  uuid not null references public.machine_programs(id) on delete cascade,
  primary key (service_id, machine_program_id)
);

alter table public.service_machine_programs enable row level security;

create policy "service_machine_programs_select"
  on public.service_machine_programs for select
  using (auth.uid() is not null);

-- ─────────────────────────────────────────────
-- RESOURCE ASSIGNMENTS
-- Prevents double-booking of machines/stations
-- ─────────────────────────────────────────────
create table public.resource_assignments (
  id              uuid        primary key default gen_random_uuid(),
  work_order_id   uuid        not null references public.work_orders(id) on delete cascade,
  resource_type   text        not null check (resource_type in ('workstation','equipment')),
  resource_id     uuid        not null,
  assigned_at     timestamptz not null default now(),
  released_at     timestamptz,
  assigned_by     uuid        references public.profiles(id) on delete set null
);

comment on table public.resource_assignments is 'Tracks machine/station reservations. Use assign_equipment() RPC to prevent concurrent booking.';

create index idx_resource_assignments_resource on public.resource_assignments(resource_id, released_at);
create index idx_resource_assignments_order on public.resource_assignments(work_order_id);

alter table public.resource_assignments enable row level security;

create policy "resource_assignments_select"
  on public.resource_assignments for select
  using (
    work_order_id in (
      select id from public.work_orders
      where branch_id in (select public.get_accessible_branch_ids())
    )
  );

-- ─────────────────────────────────────────────
-- RPC: Assign equipment to order (concurrency-safe)
-- ─────────────────────────────────────────────
create or replace function public.assign_equipment(
  p_work_order_id uuid,
  p_resource_type text,
  p_resource_id   uuid
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_assignment_id uuid;
  v_branch_id     uuid;
begin
  -- Get order's branch
  select branch_id into v_branch_id
  from public.work_orders
  where id = p_work_order_id;

  -- Permission check
  if v_branch_id not in (select public.get_accessible_branch_ids()) then
    raise exception 'Access denied to this order';
  end if;

  -- Check if resource is already assigned (not released)
  if exists (
    select 1 from public.resource_assignments
    where resource_id = p_resource_id
      and released_at is null
      and work_order_id <> p_work_order_id  -- can re-assign to same order
  ) then
    raise exception 'Resource is already assigned to another order';
  end if;

  -- Create assignment
  insert into public.resource_assignments (
    work_order_id, resource_type, resource_id, assigned_by
  ) values (
    p_work_order_id, p_resource_type, p_resource_id, auth.uid()
  )
  returning id into v_assignment_id;

  -- Update equipment status
  if p_resource_type = 'equipment' then
    update public.equipment
    set status = 'occupied'
    where id = p_resource_id;
  elsif p_resource_type = 'workstation' then
    update public.workstations
    set status = 'occupied'
    where id = p_resource_id;
  end if;

  return v_assignment_id;
end;
$$;

-- ─────────────────────────────────────────────
-- RPC: Release equipment
-- ─────────────────────────────────────────────
create or replace function public.release_equipment(
  p_work_order_id uuid,
  p_resource_id   uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_resource_type text;
begin
  -- Release assignment
  update public.resource_assignments
  set released_at = now()
  where work_order_id = p_work_order_id
    and resource_id = p_resource_id
    and released_at is null
  returning resource_type into v_resource_type;

  -- Update resource status to available
  if v_resource_type = 'equipment' then
    update public.equipment set status = 'available' where id = p_resource_id;
  elsif v_resource_type = 'workstation' then
    update public.workstations set status = 'available' where id = p_resource_id;
  end if;
end;
$$;

-- ─────────────────────────────────────────────
-- SEED: Workstations and Equipment for Escalón
-- ─────────────────────────────────────────────
insert into public.workstations (organization_id, branch_id, code, name, type) values
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0001-000000000001', 'RECEP',  'Recepción',          'reception'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0001-000000000001', 'TUN-1',  'Túnel Lavado 1',     'wash'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0001-000000000001', 'ASPI-1', 'Bahía Aspirado 1',   'vacuum'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0001-000000000001', 'ASPI-2', 'Bahía Aspirado 2',   'vacuum'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0001-000000000001', 'DET-1',  'Bahía Detailing 1',  'detailing'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0001-000000000001', 'SEC-1',  'Bahía Secado 1',     'drying'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0001-000000000001', 'QC-1',   'Control Calidad',    'quality_control');

insert into public.equipment (organization_id, branch_id, code, name, equipment_type) values
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0001-000000000001', 'LAV-TUN-01', 'Lavadora Túnel Principal', 'tunnel_washer'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0001-000000000001', 'PRES-01',    'Lavadora Presión 1',       'pressure_washer'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0001-000000000001', 'PRES-02',    'Lavadora Presión 2',       'pressure_washer'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0001-000000000001', 'ASPI-01',    'Aspiradora Industrial 1',  'vacuum'),
  ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0001-000000000001', 'ASPI-02',    'Aspiradora Industrial 2',  'vacuum');
-- ============================================================
-- Migration: 0012_quality.sql
-- Description: Configurable quality control checklists
--   and per-order quality check records.
-- ============================================================

-- ─────────────────────────────────────────────
-- QUALITY CHECKLISTS (configurables por organización)
-- ─────────────────────────────────────────────
create table public.quality_checklists (
  id              uuid    primary key default gen_random_uuid(),
  organization_id uuid    not null references public.organizations(id) on delete restrict,
  name            text    not null,
  active          boolean not null default true,
  created_at      timestamptz not null default now()
);

alter table public.quality_checklists enable row level security;

create policy "quality_checklists_select"
  on public.quality_checklists for select
  using (organization_id = public.get_my_organization_id());

create policy "quality_checklists_manage"
  on public.quality_checklists for all
  using (
    organization_id = public.get_my_organization_id()
    and public.has_permission('quality.manage')
  );

-- ─────────────────────────────────────────────
-- CHECKLIST ITEMS
-- ─────────────────────────────────────────────
create table public.quality_check_items (
  id              uuid    primary key default gen_random_uuid(),
  checklist_id    uuid    not null references public.quality_checklists(id) on delete cascade,
  name            text    not null,
  description     text,
  sort_order      int     not null default 0,
  required        boolean not null default false,
  active          boolean not null default true
);

alter table public.quality_check_items enable row level security;
create index idx_quality_check_items_checklist on public.quality_check_items(checklist_id);

create policy "quality_check_items_select"
  on public.quality_check_items for select
  using (
    checklist_id in (
      select id from public.quality_checklists
      where organization_id = public.get_my_organization_id()
    )
  );

-- ─────────────────────────────────────────────
-- WORK ORDER QUALITY CHECKS
-- ─────────────────────────────────────────────
create table public.work_order_quality_checks (
  id              uuid        primary key default gen_random_uuid(),
  work_order_id   uuid        not null references public.work_orders(id) on delete cascade,
  checklist_id    uuid        not null references public.quality_checklists(id),
  item_id         uuid        not null references public.quality_check_items(id),
  passed          boolean,
  notes           text,
  checked_by      uuid,       -- FK to employees added in 0018
  checked_at      timestamptz not null default now()
);

alter table public.work_order_quality_checks enable row level security;
create index idx_wo_quality_checks_order on public.work_order_quality_checks(work_order_id);

create policy "wo_quality_checks_select"
  on public.work_order_quality_checks for select
  using (
    work_order_id in (
      select id from public.work_orders
      where branch_id in (select public.get_accessible_branch_ids())
    )
    and public.has_permission('quality.read')
  );

create policy "wo_quality_checks_insert"
  on public.work_order_quality_checks for insert
  with check (
    work_order_id in (
      select id from public.work_orders
      where branch_id in (select public.get_accessible_branch_ids())
    )
    and public.has_permission('quality.manage')
  );

-- ─────────────────────────────────────────────
-- SEED: Default Quality Checklist for CORSA
-- ─────────────────────────────────────────────
insert into public.quality_checklists (id, organization_id, name) values
  ('00000000-0000-0000-0005-000000000001',
   '00000000-0000-0000-0000-000000000001',
   'Checklist Estándar de Calidad');

insert into public.quality_check_items (checklist_id, name, sort_order, required) values
  ('00000000-0000-0000-0005-000000000001', 'Carrocería exterior limpia',      1, true),
  ('00000000-0000-0000-0005-000000000001', 'Vidrios sin manchas',             2, true),
  ('00000000-0000-0000-0005-000000000001', 'Rines y llantas limpias',         3, true),
  ('00000000-0000-0000-0005-000000000001', 'Interior aspirado correctamente', 4, true),
  ('00000000-0000-0000-0005-000000000001', 'Tablero y consola limpios',       5, true),
  ('00000000-0000-0000-0005-000000000001', 'Alfombras limpias',               6, true),
  ('00000000-0000-0000-0005-000000000001', 'Aromatizante aplicado',           7, false),
  ('00000000-0000-0000-0005-000000000001', 'Protector de llantas aplicado',   8, false),
  ('00000000-0000-0000-0005-000000000001', 'Sin daños no reportados',         9, true);
-- ============================================================
-- Migration: 0013_payments.sql
-- Description: Payment methods, payments, payment allocations,
--   and tips. Supports split (mixed) payments.
--   Financial mutations go through register_payment() RPC.
-- ============================================================

-- ─────────────────────────────────────────────
-- PAYMENT METHODS
-- ─────────────────────────────────────────────
create table public.payment_methods (
  id              uuid    primary key default gen_random_uuid(),
  organization_id uuid    not null references public.organizations(id) on delete restrict,
  branch_id       uuid    references public.branches(id) on delete cascade,  -- null = all branches
  code            text    not null,
  name            text    not null,
  type            text    not null check (type in ('cash','card','bank_transfer','corporate_credit','membership','coupon','other')),
  requires_reference boolean not null default false,
  active          boolean not null default true,
  sort_order      int     not null default 0,

  constraint payment_methods_org_code_unique unique (organization_id, code)
);

alter table public.payment_methods enable row level security;

create policy "payment_methods_select"
  on public.payment_methods for select
  using (organization_id = public.get_my_organization_id());

create policy "payment_methods_manage"
  on public.payment_methods for all
  using (
    organization_id = public.get_my_organization_id()
    and public.has_permission('settings.manage')
  );

-- ─────────────────────────────────────────────
-- PAYMENTS
-- ─────────────────────────────────────────────
create table public.payments (
  id                  uuid          primary key default gen_random_uuid(),
  organization_id     uuid          not null references public.organizations(id) on delete restrict,
  branch_id           uuid          not null references public.branches(id) on delete restrict,
  payment_method_id   uuid          not null references public.payment_methods(id) on delete restrict,
  amount              numeric(10,2) not null check (amount > 0),
  amount_tendered     numeric(10,2),            -- for cash: amount given by customer
  change_given        numeric(10,2),            -- for cash: change returned (not income)
  currency            text          not null default 'USD',
  status              text          not null default 'approved'
                                    check (status in ('pending','approved','rejected','voided','refunded')),
  provider            text,                     -- 'cash', 'terminal_credomatic', etc. (abstraction)
  external_reference  text,                     -- terminal receipt number, bank transfer ref
  authorization_code  text,                     -- card auth code (NEVER store full card number)
  idempotency_key     text          unique,      -- for safe retries
  received_by         uuid          references public.profiles(id) on delete set null,
  created_at          timestamptz   not null default now(),
  voided_at           timestamptz,
  voided_by           uuid          references public.profiles(id) on delete set null,
  void_reason         text,

  -- Integrity: change only makes sense for cash and must not exceed tendered
  constraint payments_cash_change_check check (
    change_given is null
    or (amount_tendered is not null and change_given = amount_tendered - amount)
  )
);

comment on table public.payments is 'Individual payment transactions. One order can have multiple payments (split payment).';
comment on column public.payments.authorization_code is 'Card authorization code only. NEVER store full card number (PCI compliance).';
comment on column public.payments.idempotency_key is 'Use for safe retries. Prevents double-charging on network errors.';

create index idx_payments_branch_created on public.payments(branch_id, created_at desc);
create index idx_payments_status on public.payments(branch_id, status);

alter table public.payments enable row level security;

create policy "payments_select"
  on public.payments for select
  using (
    branch_id in (select public.get_accessible_branch_ids())
    and public.has_permission('payments.create')  -- at minimum need payment perm to see
  );

-- Payments are written only via register_payment() RPC (security definer)

-- ─────────────────────────────────────────────
-- PAYMENT ALLOCATIONS
-- Links payments to work orders (or future invoices)
-- Enables split payment across multiple orders eventually
-- ─────────────────────────────────────────────
create table public.payment_allocations (
  id              uuid          primary key default gen_random_uuid(),
  payment_id      uuid          not null references public.payments(id) on delete restrict,
  work_order_id   uuid          references public.work_orders(id) on delete restrict,
  invoice_id      uuid,         -- FK reserved for future invoices table
  amount          numeric(10,2) not null check (amount > 0),
  created_at      timestamptz   not null default now()
);

comment on table public.payment_allocations is 'Links payments to work orders. An order is paid when sum(allocations) >= order.total.';

create index idx_payment_allocations_payment on public.payment_allocations(payment_id);
create index idx_payment_allocations_order on public.payment_allocations(work_order_id);

alter table public.payment_allocations enable row level security;

create policy "payment_allocations_select"
  on public.payment_allocations for select
  using (
    payment_id in (
      select id from public.payments
      where branch_id in (select public.get_accessible_branch_ids())
    )
  );

-- ─────────────────────────────────────────────
-- TIPS
-- ─────────────────────────────────────────────
create table public.tips (
  id                  uuid          primary key default gen_random_uuid(),
  work_order_id       uuid          not null references public.work_orders(id) on delete restrict,
  payment_id          uuid          references public.payments(id) on delete set null,
  amount              numeric(10,2) not null check (amount > 0),
  distribution_type   text          not null default 'pool'
                                    check (distribution_type in ('single','pool','split')),
  notes               text,
  created_at          timestamptz   not null default now()
);

comment on table public.tips is 'Tips are tracked separately from revenue. Not included in order.total.';

alter table public.tips enable row level security;
create index idx_tips_work_order on public.tips(work_order_id);

create policy "tips_select"
  on public.tips for select
  using (
    work_order_id in (
      select id from public.work_orders
      where branch_id in (select public.get_accessible_branch_ids())
    )
  );

-- ─────────────────────────────────────────────
-- TIP DISTRIBUTIONS (to employees)
-- ─────────────────────────────────────────────
create table public.tip_distributions (
  id          uuid          primary key default gen_random_uuid(),
  tip_id      uuid          not null references public.tips(id) on delete cascade,
  employee_id uuid          not null,    -- FK added in 0018
  amount      numeric(10,2) not null check (amount > 0)
);

alter table public.tip_distributions enable row level security;

create policy "tip_distributions_select"
  on public.tip_distributions for select
  using (
    tip_id in (
      select t.id from public.tips t
      join public.work_orders wo on wo.id = t.work_order_id
      where wo.branch_id in (select public.get_accessible_branch_ids())
    )
  );

-- ─────────────────────────────────────────────
-- RPC: register_payment (transactional)
-- Processes one or more payments for a work order.
-- Handles split payment: cash + card, etc.
-- Updates order payment_status when fully paid.
-- ─────────────────────────────────────────────
create or replace function public.register_payment(
  p_work_order_id uuid,
  p_payments      jsonb,     -- [{payment_method_id, amount, amount_tendered?, external_reference?, authorization_code?, idempotency_key?}]
  p_tip_amount    numeric default 0,
  p_cash_session_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order         record;
  v_payment_item  jsonb;
  v_payment_id    uuid;
  v_pm            record;
  v_total_paid    numeric(10,2) := 0;
  v_already_paid  numeric(10,2) := 0;
  v_remaining     numeric(10,2);
  v_alloc_amount  numeric(10,2);
  v_tip_id        uuid;
  v_payment_ids   uuid[] := '{}';
begin
  -- Permission check
  if not public.has_permission('payments.create') then
    raise exception 'Permission denied: payments.create required';
  end if;

  -- Get and lock the work order
  select * into v_order
  from public.work_orders
  where id = p_work_order_id
  for update;

  if not found then
    raise exception 'Work order not found';
  end if;

  -- Branch access check
  if v_order.branch_id not in (select public.get_accessible_branch_ids()) then
    raise exception 'Access denied to this order';
  end if;

  -- Order must not be cancelled
  if v_order.status = 'cancelled' then
    raise exception 'Cannot pay a cancelled order';
  end if;

  -- Calculate already paid amount
  select coalesce(sum(pa.amount), 0) into v_already_paid
  from public.payment_allocations pa
  join public.payments p on p.id = pa.payment_id
  where pa.work_order_id = p_work_order_id
    and p.status = 'approved';

  v_remaining := v_order.total - v_already_paid;

  -- Process each payment
  for v_payment_item in select * from jsonb_array_elements(p_payments)
  loop
    -- Get payment method details
    select * into v_pm
    from public.payment_methods
    where id = (v_payment_item->>'payment_method_id')::uuid;

    if not found then
      raise exception 'Payment method not found';
    end if;

    -- Insert payment
    insert into public.payments (
      organization_id, branch_id, payment_method_id,
      amount, amount_tendered, change_given,
      currency, status, provider,
      external_reference, authorization_code,
      idempotency_key, received_by
    ) values (
      v_order.organization_id,
      v_order.branch_id,
      v_pm.id,
      (v_payment_item->>'amount')::numeric,
      (v_payment_item->>'amount_tendered')::numeric,
      case
        when v_pm.type = 'cash' and v_payment_item->>'amount_tendered' is not null
          then (v_payment_item->>'amount_tendered')::numeric - (v_payment_item->>'amount')::numeric
        else null
      end,
      'USD', 'approved', v_pm.type,
      v_payment_item->>'external_reference',
      v_payment_item->>'authorization_code',
      v_payment_item->>'idempotency_key',
      auth.uid()
    )
    returning id into v_payment_id;

    v_payment_ids := array_append(v_payment_ids, v_payment_id);

    -- Calculate allocation (cap at remaining balance)
    v_alloc_amount := least((v_payment_item->>'amount')::numeric, v_remaining);

    -- Create payment allocation
    insert into public.payment_allocations (payment_id, work_order_id, amount)
    values (v_payment_id, p_work_order_id, v_alloc_amount);

    v_total_paid := v_total_paid + v_alloc_amount;
    v_remaining  := v_remaining - v_alloc_amount;

    -- Record cash movement if we have a session
    if p_cash_session_id is not null and v_pm.type = 'cash' then
      insert into public.cash_movements (
        cash_session_id, type, amount, reference_id, description, created_by
      ) values (
        p_cash_session_id, 'sale',
        (v_payment_item->>'amount')::numeric,
        p_work_order_id,
        'Pago orden ' || v_order.order_number,
        auth.uid()
      );
    end if;
  end loop;

  -- Record tip
  if p_tip_amount > 0 then
    insert into public.tips (work_order_id, amount, distribution_type)
    values (p_work_order_id, p_tip_amount, 'pool')
    returning id into v_tip_id;

    -- Update order tip total
    update public.work_orders
    set tip_total = tip_total + p_tip_amount
    where id = p_work_order_id;
  end if;

  -- Update order payment status
  declare
    v_new_paid_total numeric(10,2);
  begin
    select coalesce(sum(pa.amount), 0) into v_new_paid_total
    from public.payment_allocations pa
    join public.payments p on p.id = pa.payment_id
    where pa.work_order_id = p_work_order_id
      and p.status = 'approved';

    update public.work_orders
    set payment_status = case
          when v_new_paid_total >= total then 'paid'
          when v_new_paid_total > 0 then 'partial'
          else 'pending'
        end,
        status = case
          when v_new_paid_total >= total and status not in ('delivered','cancelled') then 'paid'
          else status
        end,
        updated_by = auth.uid()
    where id = p_work_order_id;
  end;

  return jsonb_build_object(
    'payment_ids', v_payment_ids,
    'total_paid', v_total_paid,
    'remaining', greatest(v_remaining, 0),
    'tip_id', v_tip_id
  );
end;
$$;

comment on function public.register_payment(uuid, jsonb, numeric, uuid) is
  'Atomically registers one or more payments (split payment). Updates order payment_status. Logs cash movements.';

-- ─────────────────────────────────────────────
-- SEED: Payment methods for CORSA Escalón
-- ─────────────────────────────────────────────
insert into public.payment_methods (organization_id, code, name, type, requires_reference, sort_order) values
  ('00000000-0000-0000-0000-000000000001', 'CASH',     'Efectivo',             'cash',             false, 1),
  ('00000000-0000-0000-0000-000000000001', 'CARD',     'Tarjeta',              'card',             true,  2),
  ('00000000-0000-0000-0000-000000000001', 'TRANSFER', 'Transferencia Bancaria','bank_transfer',   true,  3),
  ('00000000-0000-0000-0000-000000000001', 'CORP',     'Crédito Corporativo',  'corporate_credit', false, 4),
  ('00000000-0000-0000-0000-000000000001', 'MEMBER',   'Membresía',            'membership',       false, 5),
  ('00000000-0000-0000-0000-000000000001', 'COUPON',   'Cupón',                'coupon',           true,  6);
-- ============================================================
-- Migration: 0014_cash.sql
-- Description: Cash registers, sessions, and movements.
--   Every cash transaction is logged. Closing requires
--   counting and justification for differences above tolerance.
-- ============================================================

-- ─────────────────────────────────────────────
-- CASH REGISTERS
-- ─────────────────────────────────────────────
create table public.cash_registers (
  id          uuid    primary key default gen_random_uuid(),
  branch_id   uuid    not null references public.branches(id) on delete restrict,
  name        text    not null,
  code        text    not null,
  active      boolean not null default true,

  constraint cash_registers_branch_code_unique unique (branch_id, code)
);

alter table public.cash_registers enable row level security;

create policy "cash_registers_select"
  on public.cash_registers for select
  using (
    branch_id in (select public.get_accessible_branch_ids())
    and public.has_permission('cash.open')
  );

-- ─────────────────────────────────────────────
-- CASH SESSIONS (Turnos de caja)
-- ─────────────────────────────────────────────
create table public.cash_sessions (
  id                  uuid          primary key default gen_random_uuid(),
  cash_register_id    uuid          not null references public.cash_registers(id) on delete restrict,
  opened_at           timestamptz   not null default now(),
  opened_by           uuid          not null references public.profiles(id) on delete restrict,
  opening_amount      numeric(10,2) not null default 0 check (opening_amount >= 0),
  closed_at           timestamptz,
  closed_by           uuid          references public.profiles(id) on delete set null,
  expected_cash       numeric(10,2),          -- calculated sum of all cash movements
  counted_cash        numeric(10,2),          -- actual cash counted at close
  difference          numeric(10,2),          -- counted - expected (negative = short)
  justification       text,                   -- required if |difference| > tolerance
  approved_by         uuid          references public.profiles(id) on delete set null,
  status              text          not null default 'open'
                                    check (status in ('open','closed','pending_approval'))
);

comment on table public.cash_sessions is 'A cash session (turn) per register. Closing validates counted vs expected.';

create index idx_cash_sessions_register on public.cash_sessions(cash_register_id);
create index idx_cash_sessions_status on public.cash_sessions(cash_register_id, status);

alter table public.cash_sessions enable row level security;

create policy "cash_sessions_select"
  on public.cash_sessions for select
  using (
    cash_register_id in (
      select cr.id from public.cash_registers cr
      where cr.branch_id in (select public.get_accessible_branch_ids())
    )
    and public.has_permission('cash.open')
  );

-- ─────────────────────────────────────────────
-- CASH MOVEMENTS
-- Every cash transaction creates a movement record.
-- This is an append-only ledger.
-- ─────────────────────────────────────────────
create table public.cash_movements (
  id                uuid          primary key default gen_random_uuid(),
  cash_session_id   uuid          not null references public.cash_sessions(id) on delete restrict,
  type              text          not null
                                  check (type in ('sale','cash_in','cash_out','refund','adjustment','deposit')),
  amount            numeric(10,2) not null,   -- positive = cash in, negative = cash out
  reference_id      uuid,                     -- work_order_id, payment_id, etc.
  reference_type    text,                     -- 'work_order', 'payment', 'expense'
  description       text          not null,
  created_by        uuid          references public.profiles(id) on delete set null,
  created_at        timestamptz   not null default now()
);

comment on table public.cash_movements is 'Append-only cash ledger. Never delete or update. Closing session calculates expected_cash from this.';

create index idx_cash_movements_session on public.cash_movements(cash_session_id);
create index idx_cash_movements_created on public.cash_movements(cash_session_id, created_at);

alter table public.cash_movements enable row level security;

create policy "cash_movements_select"
  on public.cash_movements for select
  using (
    cash_session_id in (
      select cs.id from public.cash_sessions cs
      join public.cash_registers cr on cr.id = cs.cash_register_id
      where cr.branch_id in (select public.get_accessible_branch_ids())
    )
    and public.has_permission('cash.open')
  );

-- ─────────────────────────────────────────────
-- RPC: Open cash session
-- ─────────────────────────────────────────────
create or replace function public.open_cash_session(
  p_cash_register_id uuid,
  p_opening_amount   numeric default 0
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session_id uuid;
  v_branch_id  uuid;
begin
  if not public.has_permission('cash.open') then
    raise exception 'Permission denied: cash.open required';
  end if;

  -- Get branch for this register
  select branch_id into v_branch_id
  from public.cash_registers
  where id = p_cash_register_id and active = true;

  if not found then
    raise exception 'Cash register not found or inactive';
  end if;

  if v_branch_id not in (select public.get_accessible_branch_ids()) then
    raise exception 'Access denied to this branch';
  end if;

  -- Check no open session exists for this register
  if exists (
    select 1 from public.cash_sessions
    where cash_register_id = p_cash_register_id
      and status = 'open'
  ) then
    raise exception 'There is already an open session for this register';
  end if;

  insert into public.cash_sessions (
    cash_register_id, opened_by, opening_amount, status
  ) values (
    p_cash_register_id, auth.uid(), p_opening_amount, 'open'
  )
  returning id into v_session_id;

  -- Record opening movement
  insert into public.cash_movements (
    cash_session_id, type, amount, description, created_by
  ) values (
    v_session_id, 'cash_in', p_opening_amount, 'Apertura de caja', auth.uid()
  );

  return v_session_id;
end;
$$;

-- ─────────────────────────────────────────────
-- RPC: Close cash session (transactional)
-- Calculates expected, records difference, requires
-- justification if difference exceeds tolerance.
-- TODO(security): Make tolerance configurable per org instead of hardcoded $1.00
-- ─────────────────────────────────────────────
create or replace function public.close_cash_session(
  p_session_id    uuid,
  p_counted_cash  numeric,
  p_justification text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session       record;
  v_expected      numeric(10,2);
  v_difference    numeric(10,2);
  v_tolerance     numeric(10,2) := 1.00;  -- TODO(security): make configurable per org
  v_new_status    text;
begin
  if not public.has_permission('cash.close') then
    raise exception 'Permission denied: cash.close required';
  end if;

  -- Lock the session
  select * into v_session
  from public.cash_sessions
  where id = p_session_id and status = 'open'
  for update;

  if not found then
    raise exception 'Session not found or already closed';
  end if;

  -- Calculate expected cash from movements
  select coalesce(sum(amount), 0) into v_expected
  from public.cash_movements
  where cash_session_id = p_session_id;

  v_difference := p_counted_cash - v_expected;

  -- Require justification if difference exceeds tolerance
  if abs(v_difference) > v_tolerance and p_justification is null then
    raise exception 'Justification required: difference of % exceeds tolerance of %',
      v_difference, v_tolerance;
  end if;

  -- Determine status
  if abs(v_difference) > v_tolerance then
    v_new_status := 'pending_approval';  -- requires supervisor approval
  else
    v_new_status := 'closed';
  end if;

  -- Update session
  update public.cash_sessions
  set closed_at     = now(),
      closed_by     = auth.uid(),
      expected_cash = v_expected,
      counted_cash  = p_counted_cash,
      difference    = v_difference,
      justification = p_justification,
      status        = v_new_status
  where id = p_session_id;

  return jsonb_build_object(
    'session_id',   p_session_id,
    'expected',     v_expected,
    'counted',      p_counted_cash,
    'difference',   v_difference,
    'status',       v_new_status,
    'needs_approval', (v_new_status = 'pending_approval')
  );
end;
$$;

comment on function public.close_cash_session(uuid, numeric, text) is
  'Closes a cash session. Calculates expected vs counted. Requires justification if difference > tolerance.';

-- ─────────────────────────────────────────────
-- SEED: Cash register for Escalón
-- ─────────────────────────────────────────────
insert into public.cash_registers (branch_id, name, code) values
  ('00000000-0000-0000-0001-000000000001', 'Caja Principal Escalón', 'CAJA-01');
