-- ============================================================
-- Migration: 0010_work_orders.sql
-- Description: Core operational entity — work orders, items,
--   status history, check-in, assignments, and reworks.
--   Order number generation is concurrency-safe.
-- ============================================================

-- ─────────────────────────────────────────────
-- ORDER NUMBER SEQUENCE TABLE
-- One row per (organization, branch, year) — for safe concurrent number generation
-- ─────────────────────────────────────────────
create table public.order_number_sequences (
  organization_id uuid not null references public.organizations(id) on delete restrict,
  branch_code     text not null,
  year            int  not null,
  last_sequence   int  not null default 0,
  primary key (organization_id, branch_code, year)
);

comment on table public.order_number_sequences is 'Counter table for generating unique, readable order numbers. Use generate_order_number() RPC only.';

-- ─────────────────────────────────────────────
-- RPC: Generate order number (concurrency-safe)
-- Uses SELECT FOR UPDATE to prevent race conditions
-- Format: ESC-2026-000001
-- ─────────────────────────────────────────────
create or replace function public.generate_order_number(
  p_organization_id uuid,
  p_branch_code     text,
  p_year            int default extract(year from now())::int
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_next_seq int;
begin
  -- Upsert sequence row and lock it for this transaction
  insert into public.order_number_sequences (organization_id, branch_code, year, last_sequence)
  values (p_organization_id, p_branch_code, p_year, 0)
  on conflict (organization_id, branch_code, year) do nothing;

  -- Lock the row and increment atomically
  update public.order_number_sequences
  set last_sequence = last_sequence + 1
  where organization_id = p_organization_id
    and branch_code = p_branch_code
    and year = p_year
  returning last_sequence into v_next_seq;

  -- Format: ESC-2026-000001
  return p_branch_code || '-' || p_year || '-' || lpad(v_next_seq::text, 6, '0');
end;
$$;

-- ─────────────────────────────────────────────
-- WORK ORDERS
-- ─────────────────────────────────────────────
create table public.work_orders (
  id              uuid        primary key default gen_random_uuid(),
  organization_id uuid        not null references public.organizations(id) on delete restrict,
  branch_id       uuid        not null references public.branches(id) on delete restrict,
  order_number    text        not null unique,
  customer_id     uuid        references public.customers(id) on delete restrict,
  vehicle_id      uuid        references public.vehicles(id) on delete restrict,
  appointment_id  uuid,                    -- FK added after appointments table
  source          text        not null default 'walk_in'
                              check (source in ('walk_in','appointment','fleet','online','phone')),
  priority        text        not null default 'normal'
                              check (priority in ('normal','high','vip')),
  status          text        not null default 'received'
                              check (status in (
                                'received','waiting','washing','drying_detailing',
                                'quality_control','ready','paid','delivered','cancelled'
                              )),
  -- Timestamps for each status transition
  checked_in_at   timestamptz,
  started_at      timestamptz,
  completed_at    timestamptz,
  ready_at        timestamptz,
  delivered_at    timestamptz,
  cancelled_at    timestamptz,

  -- Financials (denormalized for performance; always recalculated before save)
  subtotal        numeric(10,2) not null default 0,
  discount_total  numeric(10,2) not null default 0,
  tax_total       numeric(10,2) not null default 0,
  tip_total       numeric(10,2) not null default 0,
  total           numeric(10,2) not null default 0,
  payment_status  text        not null default 'pending'
                              check (payment_status in ('pending','partial','paid','refunded')),
  notes           text,
  created_by      uuid        references public.profiles(id) on delete set null,
  updated_by      uuid        references public.profiles(id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

comment on table public.work_orders is 'Core operational entity. Every vehicle visit generates one work order.';
comment on column public.work_orders.order_number is 'Human-readable unique number (e.g. ESC-2026-000001). Generated by generate_order_number() RPC.';
comment on column public.work_orders.subtotal is 'Sum of item totals before tax/discount. Recalculated on every item change.';

create trigger work_orders_updated_at
  before update on public.work_orders
  for each row execute function public.set_updated_at();

create index idx_work_orders_org_branch on public.work_orders(organization_id, branch_id);
create index idx_work_orders_branch_status on public.work_orders(branch_id, status);
create index idx_work_orders_branch_created on public.work_orders(branch_id, created_at desc);
create index idx_work_orders_customer_id on public.work_orders(customer_id);
create index idx_work_orders_vehicle_id on public.work_orders(vehicle_id);
create index idx_work_orders_payment_status on public.work_orders(branch_id, payment_status);

alter table public.work_orders enable row level security;

create policy "work_orders_select"
  on public.work_orders for select
  using (
    branch_id in (select public.get_accessible_branch_ids())
    and public.has_permission('orders.read')
  );

-- Insert/update goes through create_work_order() RPC
-- Direct writes blocked; RPC uses security definer
create policy "work_orders_update_direct"
  on public.work_orders for update
  using (
    branch_id in (select public.get_accessible_branch_ids())
    and public.has_permission('orders.update')
  );

-- ─────────────────────────────────────────────
-- WORK ORDER ITEMS
-- ─────────────────────────────────────────────
create table public.work_order_items (
  id                    uuid          primary key default gen_random_uuid(),
  work_order_id         uuid          not null references public.work_orders(id) on delete cascade,
  service_id            uuid          not null references public.services(id) on delete restrict,
  description_snapshot  text          not null,   -- service name at time of sale (immutable)
  price_snapshot        numeric(10,2) not null,   -- listed price (before discount/tax)
  quantity              int           not null default 1 check (quantity > 0),
  unit_price            numeric(10,2) not null,   -- effective unit price (may equal price_snapshot)
  discount_amount       numeric(10,2) not null default 0 check (discount_amount >= 0),
  tax_amount            numeric(10,2) not null default 0 check (tax_amount >= 0),
  total                 numeric(10,2) not null,   -- (unit_price * qty) - discount + tax
  membership_covered    boolean       not null default false,
  membership_usage_id   uuid,                     -- FK added after memberships table
  sort_order            int           not null default 0,
  created_at            timestamptz   not null default now()
);

comment on table public.work_order_items is 'Line items of a work order. description_snapshot and price_snapshot are immutable records of the sale.';

create index idx_work_order_items_work_order on public.work_order_items(work_order_id);
create index idx_work_order_items_service on public.work_order_items(service_id);

alter table public.work_order_items enable row level security;

create policy "work_order_items_select"
  on public.work_order_items for select
  using (
    work_order_id in (
      select id from public.work_orders
      where branch_id in (select public.get_accessible_branch_ids())
    )
    and public.has_permission('orders.read')
  );

-- ─────────────────────────────────────────────
-- WORK ORDER STATUS HISTORY
-- ─────────────────────────────────────────────
create table public.work_order_status_history (
  id              uuid        primary key default gen_random_uuid(),
  work_order_id   uuid        not null references public.work_orders(id) on delete cascade,
  previous_status text,
  new_status      text        not null,
  changed_by      uuid        references public.profiles(id) on delete set null,
  changed_at      timestamptz not null default now(),
  notes           text,
  source          text        not null default 'manual'
                              check (source in ('manual','system','api'))
);

comment on table public.work_order_status_history is 'Immutable audit trail of all status transitions. Used for operational KPI calculations.';

create index idx_wo_status_history_order on public.work_order_status_history(work_order_id);

alter table public.work_order_status_history enable row level security;

create policy "wo_status_history_select"
  on public.work_order_status_history for select
  using (
    work_order_id in (
      select id from public.work_orders
      where branch_id in (select public.get_accessible_branch_ids())
    )
    and public.has_permission('orders.read')
  );

-- ─────────────────────────────────────────────
-- TRIGGER: Auto-record status changes
-- ─────────────────────────────────────────────
create or replace function public.record_order_status_change()
returns trigger language plpgsql as $$
begin
  if new.status <> old.status then
    insert into public.work_order_status_history (
      work_order_id, previous_status, new_status, changed_by, source
    ) values (
      new.id, old.status, new.status, new.updated_by, 'manual'
    );

    -- Update relevant timestamp
    case new.status
      when 'washing'  then new.started_at = coalesce(new.started_at, now());
      when 'ready'    then new.ready_at = now();
      when 'paid'     then null;  -- set by payment RPC
      when 'delivered' then new.delivered_at = now();
      when 'cancelled' then new.cancelled_at = now();
      else null;
    end case;
  end if;
  return new;
end;
$$;

create trigger work_order_status_change
  before update on public.work_orders
  for each row execute function public.record_order_status_change();

-- ─────────────────────────────────────────────
-- VEHICLE CHECK-IN
-- ─────────────────────────────────────────────
create table public.vehicle_checkins (
  id                    uuid        primary key default gen_random_uuid(),
  work_order_id         uuid        not null unique references public.work_orders(id) on delete cascade,
  mileage               int,
  fuel_level            int         check (fuel_level between 0 and 8),  -- octavos de tanque
  valuables_declared    text,
  existing_damage_notes text,
  general_notes         text,
  received_by           uuid        references public.profiles(id) on delete set null,
  created_at            timestamptz not null default now()
);

comment on table public.vehicle_checkins is 'Vehicle condition at reception. One per work order. Photos in vehicle_media.';
comment on column public.vehicle_checkins.fuel_level is 'Fuel level in eighths (0-8). 8 = full tank.';

alter table public.vehicle_checkins enable row level security;

create policy "checkins_select"
  on public.vehicle_checkins for select
  using (
    work_order_id in (
      select id from public.work_orders
      where branch_id in (select public.get_accessible_branch_ids())
    )
    and public.has_permission('orders.read')
  );

-- ─────────────────────────────────────────────
-- WORK ORDER ASSIGNMENTS (employee → work)
-- ─────────────────────────────────────────────
create table public.work_order_assignments (
  id                  uuid        primary key default gen_random_uuid(),
  work_order_id       uuid        not null references public.work_orders(id) on delete cascade,
  work_order_item_id  uuid        references public.work_order_items(id) on delete cascade,
  employee_id         uuid        not null,    -- FK added after employees table in 0018
  role                text        not null,    -- 'washer', 'detailer', 'supervisor'
  started_at          timestamptz,
  completed_at        timestamptz,
  notes               text
);

comment on table public.work_order_assignments is 'Records which employee performed which service on which order. Source for employee KPIs.';

create index idx_wo_assignments_order on public.work_order_assignments(work_order_id);
create index idx_wo_assignments_employee on public.work_order_assignments(employee_id);

alter table public.work_order_assignments enable row level security;

create policy "wo_assignments_select"
  on public.work_order_assignments for select
  using (
    work_order_id in (
      select id from public.work_orders
      where branch_id in (select public.get_accessible_branch_ids())
    )
    and public.has_permission('orders.read')
  );

-- ─────────────────────────────────────────────
-- WORK ORDER REWORKS
-- ─────────────────────────────────────────────
create table public.work_order_reworks (
  id                      uuid        primary key default gen_random_uuid(),
  work_order_id           uuid        not null references public.work_orders(id) on delete restrict,
  work_order_item_id      uuid        references public.work_order_items(id),
  service_id              uuid        references public.services(id),
  reason                  text        not null,
  responsible_employee_id uuid,       -- FK added after employees table
  requested_by            uuid        references public.profiles(id) on delete set null,
  created_at              timestamptz not null default now(),
  completed_at            timestamptz
);

comment on table public.work_order_reworks is 'Records rework events. Never revert status directly — always log the rework event.';

alter table public.work_order_reworks enable row level security;
create index idx_wo_reworks_order on public.work_order_reworks(work_order_id);

create policy "wo_reworks_select"
  on public.work_order_reworks for select
  using (
    work_order_id in (
      select id from public.work_orders
      where branch_id in (select public.get_accessible_branch_ids())
    )
    and public.has_permission('quality.read')
  );

-- ─────────────────────────────────────────────
-- RPC: Create work order (transactional)
-- Creates order + items + initial status history
-- ─────────────────────────────────────────────
create or replace function public.create_work_order(
  p_branch_id     uuid,
  p_customer_id   uuid,
  p_vehicle_id    uuid,
  p_source        text default 'walk_in',
  p_priority      text default 'normal',
  p_notes         text default null,
  p_services      jsonb default '[]'::jsonb   -- [{service_id, quantity, unit_price, discount_amount}]
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org_id        uuid;
  v_branch_code   text;
  v_order_number  text;
  v_order_id      uuid;
  v_subtotal      numeric(10,2) := 0;
  v_tax_total     numeric(10,2) := 0;
  v_tax_rate      numeric(5,4) := 0;
  v_total         numeric(10,2) := 0;
  v_item          jsonb;
  v_service_name  text;
  v_item_total    numeric(10,2);
  v_item_tax      numeric(10,2);
  v_item_id       uuid;
  v_sort          int := 0;
begin
  -- Permission check
  if not public.has_permission('orders.create') then
    raise exception 'Permission denied: orders.create required';
  end if;

  -- Branch access check
  if p_branch_id not in (select public.get_accessible_branch_ids()) then
    raise exception 'Access denied to branch';
  end if;

  -- Get org_id and branch code
  select organization_id, code
  into v_org_id, v_branch_code
  from public.branches
  where id = p_branch_id;

  -- Get current tax rate
  select rate into v_tax_rate
  from public.tax_rates
  where organization_id = v_org_id
    and active = true
    and applicable_from <= current_date
    and (applicable_to is null or applicable_to >= current_date)
  order by applicable_from desc
  limit 1;

  -- Generate unique order number (concurrency-safe)
  v_order_number := public.generate_order_number(
    v_org_id,
    v_branch_code,
    extract(year from now())::int
  );

  -- Create the work order
  insert into public.work_orders (
    organization_id, branch_id, order_number,
    customer_id, vehicle_id, source, priority,
    notes, status, created_by
  ) values (
    v_org_id, p_branch_id, v_order_number,
    p_customer_id, p_vehicle_id, p_source, p_priority,
    p_notes, 'received', auth.uid()
  )
  returning id into v_order_id;

  -- Insert initial status history
  insert into public.work_order_status_history (
    work_order_id, previous_status, new_status, changed_by, source
  ) values (
    v_order_id, null, 'received', auth.uid(), 'system'
  );

  -- Insert service items
  for v_item in select * from jsonb_array_elements(p_services)
  loop
    v_sort := v_sort + 1;

    -- Get service name snapshot
    select name into v_service_name
    from public.services
    where id = (v_item->>'service_id')::uuid;

    -- Calculate totals
    v_item_total := (v_item->>'unit_price')::numeric * coalesce((v_item->>'quantity')::int, 1)
                    - coalesce((v_item->>'discount_amount')::numeric, 0);

    -- Apply tax only if service is taxable
    if exists (
      select 1 from public.services
      where id = (v_item->>'service_id')::uuid and taxable = true
    ) then
      v_item_tax := round(v_item_total * v_tax_rate, 2);
    else
      v_item_tax := 0;
    end if;

    insert into public.work_order_items (
      work_order_id, service_id,
      description_snapshot, price_snapshot,
      quantity, unit_price,
      discount_amount, tax_amount,
      total, sort_order
    ) values (
      v_order_id,
      (v_item->>'service_id')::uuid,
      v_service_name,
      (v_item->>'unit_price')::numeric,
      coalesce((v_item->>'quantity')::int, 1),
      (v_item->>'unit_price')::numeric,
      coalesce((v_item->>'discount_amount')::numeric, 0),
      v_item_tax,
      v_item_total + v_item_tax,
      v_sort
    )
    returning id into v_item_id;

    v_subtotal  := v_subtotal + (v_item_total);
    v_tax_total := v_tax_total + v_item_tax;
  end loop;

  v_total := v_subtotal + v_tax_total;

  -- Update order totals
  update public.work_orders
  set subtotal    = v_subtotal,
      tax_total   = v_tax_total,
      total       = v_total,
      checked_in_at = now()
  where id = v_order_id;

  return jsonb_build_object(
    'order_id',     v_order_id,
    'order_number', v_order_number,
    'subtotal',     v_subtotal,
    'tax_total',    v_tax_total,
    'total',        v_total
  );
end;
$$;

comment on function public.create_work_order(uuid, uuid, uuid, text, text, text, jsonb) is
  'Atomically creates a work order with items and initial status. Returns order ID and number.';
